baseURL = "https://portalconvocatorias.netlify.app/"
languageCode = "es-es"
title = "Portal de Subvenciones"

[sitemap]
  changefreq = "daily"
  priority = 0.7
  filename = "sitemap.xml"

[permalinks]
  grants = "/:slug/"